name: FTP Deploy

on:
  push:
    branches:
      - dev  # Trigger CI/CD on push to dev branch

jobs:
  build:
    name: Deploy to FTP
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2  # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    
    - name: Print Debug Info
      run: |
        echo "Server: ${{ secrets.FTP_SERVER }}"
        echo "Username: ${{ secrets.FTP_USERNAME }}"

    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@4.0.0  # FTP action
      with:
        server: ftp://${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
